//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 12:39:52 PM CET 
//


package xml_classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OwnedVehicleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OwnedVehicleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Schema}VehicleType">
 *       &lt;sequence>
 *         &lt;element name="DateOfFirstRegisration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocumentExpiratonDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VehicleRegistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OwnedVehicleType", propOrder = {
    "dateOfFirstRegisration",
    "documentID",
    "documentExpiratonDate",
    "vehicleRegistrationNumber"
})
public class OwnedVehicleType
    extends VehicleType
{

    @XmlElement(name = "DateOfFirstRegisration", required = true)
    protected String dateOfFirstRegisration;
    @XmlElement(name = "DocumentID", required = true)
    protected String documentID;
    @XmlElement(name = "DocumentExpiratonDate", required = true)
    protected String documentExpiratonDate;
    @XmlElement(name = "VehicleRegistrationNumber", required = true)
    protected String vehicleRegistrationNumber;

    /**
     * Gets the value of the dateOfFirstRegisration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfFirstRegisration() {
        return dateOfFirstRegisration;
    }

    /**
     * Sets the value of the dateOfFirstRegisration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfFirstRegisration(String value) {
        this.dateOfFirstRegisration = value;
    }

    /**
     * Gets the value of the documentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentID() {
        return documentID;
    }

    /**
     * Sets the value of the documentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentID(String value) {
        this.documentID = value;
    }

    /**
     * Gets the value of the documentExpiratonDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentExpiratonDate() {
        return documentExpiratonDate;
    }

    /**
     * Sets the value of the documentExpiratonDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentExpiratonDate(String value) {
        this.documentExpiratonDate = value;
    }

    /**
     * Gets the value of the vehicleRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleRegistrationNumber() {
        return vehicleRegistrationNumber;
    }

    /**
     * Sets the value of the vehicleRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleRegistrationNumber(String value) {
        this.vehicleRegistrationNumber = value;
    }

}
